services:
  - type: web
    name: icm-planlytics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_enhanced:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"